### ISSUE TITLE
typescript required?

### ISSUE THREAD

**Issue by evbo** [Yegorich555/webpack-mock-server#13]
I am getting an error that no module named typescript exists. The `webpack.mock.js` (copied from your docs) file makes no use of typescript and neither does my app, can I run without it?

Here is the error:
> Error: Cannot find module 'typescript'

**Comment by Yegorich555** [comment]
Despite you can use js instead of ts, it's impossible to use webpack-mock-server without typescript. Typescript package includes not only transpiler but module-bundler with hot-replacement also

**Comment by evbo** [comment]
ok thanks. I was trying to use this for an electron app but that doesn't seem possible running it from webpack. It seems I'd need to somehow initialize the server from within the app itself. I ended up making good use of postman for mocking instead as an immediate fix.
