### ISSUE TITLE
How-to re-compile on webpack.mock.ts changed?

### ISSUE THREAD

**Issue by hydra1983** [Yegorich555/webpack-mock-server#18]
Now, it does not recompile the ts file.

**Comment by Yegorich555** [comment]
Incredible. Thanks for attention. I'll fix it soon ;)

**Comment by Yegorich555** [comment]
@hydra1983 could you provide more details?

After investigation I noticed that it recompiles ts-file always. But if you have webpack-dev-server port 8080 and mock-server port is 8081 and you will try resend requests from the browser to :8081 it doesn't return the new result. But after some times 5-10 second it does. At the same time it's if you fetch data from :8080...

What is your experience? Could you give me details?

Also you can debug via setup  
```
{
verbose: true,
logResponses: true,
}
```

**Comment by hydra1983** [comment]
At last, I use nodemon to compile and restart the server after compilation.

```typescript
// webpack.config.js
const express = require('express');
const bodyParser = require('body-parser');
const webpackMockServer = require('@dg/webpack-mock-server');

const app = express();

const options = {
  ...webpackMockServer.defaultOptions,
  port: 4080,
  tsConfigFileName: __dirname + '/tsconfig.json',
  entry: [__dirname + '/src/webpack-mock-server.ts'],
  verbose: false,
  server: (() => {
    const mockApp = express();
    mockApp.set("json spaces", 2); // prettify json-response
    mockApp.use(bodyParser.json({ limit: '50mb' }));
    mockApp.use(bodyParser.urlencoded({ limit: '50mb', extended: true })); // support form-urlencoded
    mockApp.use(express.text()); // support ordinary text
    return mockApp;
  })()
};

webpackMockServer.use(app, options);

process.on('SIGINT', function () {
  // console.log( "\nGracefully shutting down from SIGINT (Ctrl-C)" );
  // some other closing procedures go here
  process.exit(1);
});

app.listen(options.port);
```

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "sourceMap": true,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "typeRoots": ["../node_modules/@types"],
    "lib": ["es2018", "dom"],
  },
  "include": [
    "src/**/*.ts"
  ]
}
```

Below is just a slight modification of the original lib

![image](https://user-images.githubusercontent.com/488235/125454207-ccbcbe26-aee8-47f4-a3c8-d1adfbed2225.png)
![image](https://user-images.githubusercontent.com/488235/125454226-72107902-b393-47f1-8b55-7e91e6d91cfc.png)

**Comment by Yegorich555** [comment]
@hydra1983 thank you for your attention. Fixed for now. You can check it with version [1.0.12](https://github.com/Yegorich555/webpack-mock-server/blob/master/CHANGELOG.md#1012-july-14-2021)

**Comment by hydra1983** [comment]
Got it, thank you.
